print('''"End"''',end=" ")
print("function",end=" ")
print("is",end=" ")
print("uses",end=" ")
print("to",end=" ")
print("next",end=" ")
print("printing",end=" ")
print("string",end=" ")
print("to",end=" ")
print("seating",end=" ")
print("at",end=" ")
print("the",end=" ")
print("same",end=" ")
print("line",end="")
print(".")